name: Cadens
description:
  Github Actions that returns the commit count since the last change to a line
  in a file.
author: Communi-Suggestu

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: feather
  color: yellow

# Define your inputs here.
inputs:
  file:
    description: The file to check for changes.
    required: true
  prefix:
    description:
      The prefix of the line to check for changes. Only first match is
      considered.
    required: true

# Define your outputs here.
outputs:
  count:
    description: The amount of commits since the last change to the line.

runs:
  using: node20
  main: dist/index.js
